### ISSUE TITLE
Different results for hash-map

### ISSUE THREAD

**Issue by aliseyfi75** [plai-group/daphne#1]
Hi.

The package's result when you call it with `desugar` or `graph` is different when you have a hash-map.

Here are the results:

Input: `(put (hash-map 6 5.3 1 3.2) 6 2)` 
Output of `daphne(['desugar', '-i', test.daphne'])`: `[['put', ['hash-map', 6, 5.3, 1, 3.2], 6, 2]]`
Output of `daphne(['graph','-i','test.daphne'])`: `[{}, {'V': [], 'A': {}, 'P': {}, 'Y': {}}, ['hash-map', [1, 3.2], [6, 2]]]`

So actually in the first case we have a list of `'hash-map', 6, 5.3, 1, 3.2], 6, 2`, but in the second case we have a list of `'hash-map', [1, 3.2], [6, 2]`

**Comment by whilo** [comment]
This should be solved now, if not feel free to reopen the issue.
