### ISSUE TITLE
Problems generating python-class

### ISSUE THREAD

**Issue by alexander-mead** [plai-group/daphne#2]
Trying to install `daphne` and running into issues with the `python-class` generating options. If I try
```
lein run graph -i programs/arithmetic_circuit.daphne -o output.json
```
or
```
lein run desugar -i programs/arithmetic_circuit.daphne -o output.json
```
both work, and produce the correct output, but if I try
```
pipenv run lein run python-class -i programs/arithmetic_circuit.daphne -o autogen_arithmetic_circuit.py
```
I get `autogen_arithmetic_circuit.py` created, but with only `""` in the file. If I try:
```
lein run python-class -i programs/convolution.daphne -o autogen_convolution.py
```
I get the error:
```
Syntax error (NullPointerException) compiling at (/private/var/folders/fr/c2m_v4ss6kjcbgzbqfr_z5fw0000gn/T/form-init14751265169047276845.clj:1:126).
Cannot invoke "java.util.Map$Entry.getValue()" because "e" is null

Full report at:
/var/folders/fr/c2m_v4ss6kjcbgzbqfr_z5fw0000gn/T/clojure-14375094718594195756.edn
```
I worry that I might be doing something pretty basic wrong...

**Comment by whilo** [comment]
This might be a problem with the installed `hy` version.

**Comment by alexander-mead** [comment]
I'm on mac OS and with `hy` v 0.24.0.

**Comment by whilo** [comment]
Thanks for reporting! This should be solved with the latest commit. Please open a new issue if there are still problems.
