### ISSUE TITLE
Problems with python install

### ISSUE THREAD

**Issue by alexander-mead** [plai-group/daphne#3]
I am trying to install using `pipenv` and the `requirements.txt` file. However, I can't seem to be able to get the older versions of `torch` (1.4.0) or `torchvision` (0.5.0). I get:
```
ERROR: No matching distribution found for torch==1.4.0
```
```
ERROR: No matching distribution found for torchvision==0.5.0
```
This might relate to issue #2...

**Comment by whilo** [comment]
Just to clarify, this is only needed if you want to run the continuous normalizing flow code, not if you just want to use the compiler (?). I am not sure about the older versions, I think it should also work with newer ones, but maybe it doesn't ...

**Comment by whilo** [comment]
I am not sure what to do about this, I don't think I am going to update the Python code base for now, so people who want to run the normalizing flow code will have to install these older torch versions. But if somebody is actually interested in running the code with newer versions I am happy to help.
