### ISSUE TITLE
Windows compatibility - subprocess call needs additional arg

### ISSUE THREAD

**Issue by ianrmhill** [plai-group/daphne#9]
Hello! When running Daphne on Windows, you need to add the kwarg 'shell=True' to the subprocess.run call in daphne.py line 23. May need to switch the subprocess run command depending on the OS.

**Comment by ianrmhill** [comment]
Apologies, bug in associated repository. May still be relevant to the Daphne repo however.

**Comment by whilo** [comment]
Thanks for reporting! Which associated repository is this problem in?

**Comment by ianrmhill** [comment]
It's in the CPSC 532W Homework 2 template files. I haven't yet checked whether there's a similar issue in the later homework assignments, and I didn't check whether adding the 'shell=True' arg causes issues on non-Windows systems.

Nearer the end of taking the CPSC 532W course I'd be happy to write a little bit of documentation on using Daphne and/or completing the course using Windows if that would be valuable.
